
management.security.enabled: false
security.user.name: admin
security.user.password: admin
management.security.roles: SUPERUSER

spring:
  application.name: rest-api
  profiles.active: test_local
  thymeleaf:
    prefix: classpath:/views/
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache:  false
  boot:  
    admin:  
      context-path: /sba    #配置访问路径为http://localhost:8088/sba
  #MQ
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
  file: ${spring.application.name}
  

  
---
server:
  port: 8089
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/javascript,text/css,text/xml,text/plain
    min-response-size: 2048
  tomcat:
    accept-count: 400
    uri-encoding: utf-8
    min-spare-threads: 25
    max-threads: 400
  connection-timeout: 20000

  

    

    

