
spring:
  application.name: rest-api
  profiles.active: test_local
  thymeleaf:
    prefix: classpath:/views/
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache:  false
  boot:  
    admin:  
      context-path: /sba    #配置访问路径为http://localhost:8088/sba


logging:
  file: ${spring.application.name}
  
  
---  

    
server:
    port: 8088


    

    

