
spring:
  application.name: rest-api
  profiles.active: test_local
  thymeleaf:
    prefix: classpath:/views/
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache:  false


logging:
  file: ${spring.application.name}
  
  
---  

    
server:
    port: 8088


    

    

